#! /bin/sh


$HOME/.config/bspwm/polybar/launch.sh &

$HOME/.config/bspwm/autostart.sh &

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor Virtual-1 -d 1 2 3 4 5

# BSPC Settings
bspc config border_width         5
bspc config window_gap          12
bspc config top_padding		30
bspc config bottom_padding	10
bspc config left_padding	10
bspc config right_padding	10
bspc config single_monocle	false
bspc config split_ratio		0.55
bspc config borderless_monocle	true
bspc config gapless_monocle	true
bspc config focus_follows_pointer	true
bspc config pointer_modifier	mod4
bspc config pointer_action1	move
bspc config pointer_action2	resize_slide
bspc config pointer_action3	resize_corner
bspc config remove_disabled_monitors	true
bspc config merge_overlapping_monitors	true


# Colors
bspc config normal_border_color 	"#eee5e9"
bspc config active_border_color 	"#fb6376"
bspc config focused_border_color 	"#fb6376"
bspc config presel_feedback_color 	"#01baef"
bspc config urgent_border_color 	"#ffca3a"


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
